echo "Downloading 2009 trips"
curl https://s3.amazonaws.com/data-sprints-eng-test/data-sample_data-nyctaxi-trips-2009-json_corrigido.json -o resources/data-sample_data-nyctaxi-trips-2009-json_corrigido.json
echo "Downloading 2010 trips"
curl https://s3.amazonaws.com/data-sprints-eng-test/data-sample_data-nyctaxi-trips-2010-json_corrigido.json -o resources/data-sample_data-nyctaxi-trips-2010-json_corrigido.json
echo "Downloading 2011 trips"
curl https://s3.amazonaws.com/data-sprints-eng-test/data-sample_data-nyctaxi-trips-2011-json_corrigido.json -o resources/data-sample_data-nyctaxi-trips-2011-json_corrigido.json
echo "Downloading 2012 trips"
curl https://s3.amazonaws.com/data-sprints-eng-test/data-sample_data-nyctaxi-trips-2012-json_corrigido.json -o resources/data-sample_data-nyctaxi-trips-2012-json_corrigido.json
echo "Downloading vendor lookup"
curl https://s3.amazonaws.com/data-sprints-eng-test/data-vendor_lookup-csv.csv -o resources/data-vendor_lookup-csv.csv
echo "Downloading payment lookup"
curl https://s3.amazonaws.com/data-sprints-eng-test/data-payment_lookup-csv.csv -o resources/data-payment_lookup-csv.csv